"use strict";

const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");

const DEFAULT_DATASET_PATH = path.resolve(
  process.cwd(),
  "ml_datasets",
  "reference_candidate_binary_dataset.jsonl",
);

const DEFAULT_SUMMARY_PATH = path.resolve(
  process.cwd(),
  "ml_datasets",
  "reference_candidate_binary_dataset_summary.json",
);

const VALID_CLASSIFICATIONS = new Set([
  "truePositive",
  "trueNegative",
  "falsePositive",
  "falseNegative",
]);

const POSITIVE_DESCRIPTOR_CLASSIFICATIONS = new Set([
  "truePositive",
  "falsePositive",
]);

const NEGATIVE_DESCRIPTOR_CLASSIFICATIONS = new Set([
  "trueNegative",
  "falseNegative",
]);

const POTENTIAL_LEAKAGE_PATTERNS = [
  /label/i,
  /target/i,
  /correct/i,
  /classification/i,
  /prediction/i,
  /predicted/i,
  /accepted/i,
  /rejected/i,
  /result/i,
  /truepositive/i,
  /truenegative/i,
  /falsepositive/i,
  /falsenegative/i,
];

function parseArguments(argv) {
  const options = {
    datasetPath: DEFAULT_DATASET_PATH,
    summaryPath: DEFAULT_SUMMARY_PATH,
    requireSummary: true,
    help: false,
  };

  for (let index = 0; index < argv.length; index++) {
    const argument = argv[index];

    if (argument === "--dataset") {
      options.datasetPath = path.resolve(
        process.cwd(),
        requireArgumentValue(argv, index, argument),
      );

      index++;
      continue;
    }

    if (argument === "--summary") {
      options.summaryPath = path.resolve(
        process.cwd(),
        requireArgumentValue(argv, index, argument),
      );

      index++;
      continue;
    }

    if (argument === "--no-summary") {
      options.requireSummary = false;
      continue;
    }

    if (argument === "--help" || argument === "-h") {
      options.help = true;
      continue;
    }

    throw new Error(`Unknown argument: ${argument}`);
  }

  return options;
}

function requireArgumentValue(argv, index, argumentName) {
  const value = argv[index + 1];

  if (!value || value.startsWith("--")) {
    throw new Error(`${argumentName} requires a value`);
  }

  return value;
}

function printHelp() {
  console.log(`
REFERENCE CANDIDATE BASELINE MODEL DATASET INSPECTION

Usage:
  node scripts/train_reference_candidate_baseline_model.js

Options:
  --dataset <path>
      Input JSONL dataset.

      Default:
      ./ml_datasets/reference_candidate_binary_dataset.jsonl

  --summary <path>
      Dataset summary generated by the ML dataset exporter.

      Default:
      ./ml_datasets/reference_candidate_binary_dataset_summary.json

  --no-summary
      Do not require or validate the dataset summary.

  --help, -h
      Show this help.

Current phase:
  This first version validates and inspects the dataset.
  It does not train a model yet.
`);
}

function assertFileExists(filePath, label) {
  if (!filePath || !fs.existsSync(filePath)) {
    throw new Error(`${label} not found: ${filePath}`);
  }

  const stats = fs.statSync(filePath);

  if (!stats.isFile()) {
    throw new Error(`${label} is not a file: ${filePath}`);
  }
}

function calculateFileSha256(filePath) {
  const fileBuffer = fs.readFileSync(filePath);

  return crypto.createHash("sha256").update(fileBuffer).digest("hex");
}

function readJson(filePath, label) {
  assertFileExists(filePath, label);

  const fileContents = fs.readFileSync(filePath, "utf8");

  try {
    return JSON.parse(fileContents);
  } catch (error) {
    throw new Error(
      `${label} contains invalid JSON: ${filePath}. ${error.message}`,
    );
  }
}

function loadJsonlDataset(datasetPath) {
  assertFileExists(datasetPath, "ML dataset");

  const fileContents = fs.readFileSync(datasetPath, "utf8");

  const lines = fileContents
    .split(/\r?\n/)
    .map((line, index) => ({
      lineNumber: index + 1,
      contents: line.trim(),
    }))
    .filter((line) => line.contents.length > 0);

  if (lines.length === 0) {
    throw new Error(`ML dataset is empty: ${datasetPath}`);
  }

  return lines.map(({ lineNumber, contents }) => {
    try {
      return {
        lineNumber,
        row: JSON.parse(contents),
      };
    } catch (error) {
      throw new Error(`Invalid JSONL at line ${lineNumber}: ${error.message}`);
    }
  });
}

function isPlainObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function getExpectedClassification({ label, descriptorPrediction }) {
  if (label === 1 && descriptorPrediction === 1) {
    return "truePositive";
  }

  if (label === 1 && descriptorPrediction === 0) {
    return "falseNegative";
  }

  if (label === 0 && descriptorPrediction === 1) {
    return "falsePositive";
  }

  return "trueNegative";
}

function getDescriptorPredictionFromClassification(classification) {
  if (POSITIVE_DESCRIPTOR_CLASSIFICATIONS.has(classification)) {
    return 1;
  }

  if (NEGATIVE_DESCRIPTOR_CLASSIFICATIONS.has(classification)) {
    return 0;
  }

  throw new Error(`Unsupported descriptor classification: ${classification}`);
}

function validateDatasetRow({ row, lineNumber }) {
  const errors = [];
  const warnings = [];

  if (!isPlainObject(row)) {
    return {
      errors: [`Line ${lineNumber}: row must be an object.`],
      warnings,
    };
  }

  if (
    typeof row.recognitionId !== "string" ||
    row.recognitionId.trim().length === 0
  ) {
    errors.push(
      `Line ${lineNumber}: recognitionId must be a non-empty string.`,
    );
  }

  if (typeof row.targetKanji !== "string" || row.targetKanji.length === 0) {
    errors.push(`Line ${lineNumber}: targetKanji must be a non-empty string.`);
  }

  if (typeof row.expectedKanji !== "string" || row.expectedKanji.length === 0) {
    errors.push(
      `Line ${lineNumber}: expectedKanji must be a non-empty string.`,
    );
  }

  if (
    typeof row.targetKanji === "string" &&
    typeof row.expectedKanji === "string" &&
    row.targetKanji !== row.expectedKanji
  ) {
    errors.push(
      `Line ${lineNumber}: targetKanji and expectedKanji do not match.`,
    );
  }

  if (typeof row.sampleIsCorrect !== "boolean") {
    errors.push(`Line ${lineNumber}: sampleIsCorrect must be boolean.`);
  }

  if (row.label !== 0 && row.label !== 1) {
    errors.push(`Line ${lineNumber}: label must be either 0 or 1.`);
  }

  if (
    typeof row.sampleIsCorrect === "boolean" &&
    (row.label === 0 || row.label === 1)
  ) {
    const expectedLabel = row.sampleIsCorrect ? 1 : 0;

    if (row.label !== expectedLabel) {
      errors.push(
        `Line ${lineNumber}: label=${row.label} is inconsistent with ` +
          `sampleIsCorrect=${row.sampleIsCorrect}.`,
      );
    }
  }

  if (!VALID_CLASSIFICATIONS.has(row.classification)) {
    errors.push(
      `Line ${lineNumber}: unsupported classification ` +
        `"${row.classification}".`,
    );
  }

  if (
    VALID_CLASSIFICATIONS.has(row.classification) &&
    (row.label === 0 || row.label === 1)
  ) {
    const descriptorPrediction = getDescriptorPredictionFromClassification(
      row.classification,
    );

    const expectedClassification = getExpectedClassification({
      label: row.label,
      descriptorPrediction,
    });

    if (row.classification !== expectedClassification) {
      errors.push(
        `Line ${lineNumber}: classification="${row.classification}" ` +
          `is inconsistent with label=${row.label}.`,
      );
    }
  }

  if (!isPlainObject(row.features)) {
    errors.push(`Line ${lineNumber}: features must be an object.`);

    return {
      errors,
      warnings,
    };
  }

  const featureEntries = Object.entries(row.features);

  if (featureEntries.length === 0) {
    errors.push(
      `Line ${lineNumber}: features must contain at least one feature.`,
    );
  }

  for (const [featureName, featureValue] of featureEntries) {
    if (featureName.trim().length === 0) {
      errors.push(`Line ${lineNumber}: feature name cannot be empty.`);

      continue;
    }

    if (typeof featureValue !== "number" || !Number.isFinite(featureValue)) {
      errors.push(
        `Line ${lineNumber}: feature "${featureName}" must be a finite number.`,
      );
    }
  }

  return {
    errors,
    warnings,
  };
}

function validateDatasetRows(datasetEntries) {
  const errors = [];
  const warnings = [];

  for (const datasetEntry of datasetEntries) {
    const result = validateDatasetRow(datasetEntry);

    errors.push(...result.errors);
    warnings.push(...result.warnings);
  }

  return {
    errors,
    warnings,
  };
}

function determineFeatureNames(datasetEntries) {
  const featureNames = new Set();

  for (const { row } of datasetEntries) {
    if (!isPlainObject(row.features)) {
      continue;
    }

    for (const featureName of Object.keys(row.features)) {
      featureNames.add(featureName);
    }
  }

  return [...featureNames].sort((left, right) => left.localeCompare(right));
}

function detectPotentialLeakageFeatures(featureNames) {
  return featureNames.filter((featureName) =>
    POTENTIAL_LEAKAGE_PATTERNS.some((pattern) => pattern.test(featureName)),
  );
}

function calculateFeaturePresence(datasetEntries, featureNames) {
  const presenceByFeature = Object.fromEntries(
    featureNames.map((featureName) => [featureName, 0]),
  );

  for (const { row } of datasetEntries) {
    for (const featureName of Object.keys(row.features ?? {})) {
      presenceByFeature[featureName]++;
    }
  }

  return presenceByFeature;
}

function calculateDescriptorMetrics(datasetEntries) {
  const metrics = {
    truePositive: 0,
    trueNegative: 0,
    falsePositive: 0,
    falseNegative: 0,
  };

  for (const { row } of datasetEntries) {
    if (VALID_CLASSIFICATIONS.has(row.classification)) {
      metrics[row.classification]++;
    }
  }

  const positiveCount = metrics.truePositive + metrics.falseNegative;

  const negativeCount = metrics.trueNegative + metrics.falsePositive;

  const predictedPositiveCount = metrics.truePositive + metrics.falsePositive;

  const predictedNegativeCount = metrics.trueNegative + metrics.falseNegative;

  const total = positiveCount + negativeCount;

  return {
    ...metrics,
    positiveCount,
    negativeCount,
    predictedPositiveCount,
    predictedNegativeCount,
    accuracy: safeDivide(metrics.truePositive + metrics.trueNegative, total),
    recall: safeDivide(metrics.truePositive, positiveCount),
    specificity: safeDivide(metrics.trueNegative, negativeCount),
    precision: safeDivide(metrics.truePositive, predictedPositiveCount),
    falseNegativeRate: safeDivide(metrics.falseNegative, positiveCount),
    falsePositiveRate: safeDivide(metrics.falsePositive, negativeCount),
  };
}

function safeDivide(numerator, denominator) {
  if (denominator === 0) {
    return null;
  }

  return numerator / denominator;
}

function buildDatasetInspection({ datasetPath, datasetEntries, featureNames }) {
  const rows = datasetEntries.map((entry) => entry.row);

  const targetKanjis = [...new Set(rows.map((row) => row.targetKanji))].sort(
    (left, right) => left.localeCompare(right),
  );

  const positiveCount = rows.filter((row) => row.label === 1).length;

  const negativeCount = rows.filter((row) => row.label === 0).length;

  const classificationCounts = {};

  for (const row of rows) {
    classificationCounts[row.classification] =
      (classificationCounts[row.classification] ?? 0) + 1;
  }

  const featuresPerRow = rows.map(
    (row) => Object.keys(row.features ?? {}).length,
  );

  const uniqueRecognitionIds = new Set(rows.map((row) => row.recognitionId));

  const featurePresence = calculateFeaturePresence(
    datasetEntries,
    featureNames,
  );

  const alwaysPresentFeatures = featureNames.filter(
    (featureName) => featurePresence[featureName] === rows.length,
  );

  const sparseFeatures = featureNames.filter(
    (featureName) => featurePresence[featureName] < rows.length,
  );

  return {
    datasetPath,
    datasetSha256: calculateFileSha256(datasetPath),
    rowCount: rows.length,
    uniqueRecognitionIdCount: uniqueRecognitionIds.size,
    duplicateRecognitionIdCount: rows.length - uniqueRecognitionIds.size,
    targetKanjiCount: targetKanjis.length,
    targetKanjis,
    positiveCount,
    negativeCount,
    classificationCounts,
    featureCount: featureNames.length,
    featureNames,
    featuresPerRow: {
      minimum: Math.min(...featuresPerRow),
      maximum: Math.max(...featuresPerRow),
      average:
        featuresPerRow.reduce((total, count) => total + count, 0) /
        featuresPerRow.length,
    },
    alwaysPresentFeatureCount: alwaysPresentFeatures.length,
    sparseFeatureCount: sparseFeatures.length,
    alwaysPresentFeatures,
    potentialLeakageFeatures: detectPotentialLeakageFeatures(featureNames),
    descriptorBaselineMetrics: calculateDescriptorMetrics(datasetEntries),
  };
}

function compareArrays(left, right) {
  if (!Array.isArray(left) || !Array.isArray(right)) {
    return false;
  }

  if (left.length !== right.length) {
    return false;
  }

  const normalizedLeft = [...left].sort();
  const normalizedRight = [...right].sort();

  return normalizedLeft.every(
    (value, index) => value === normalizedRight[index],
  );
}

function compareInspectionWithSummary({ inspection, summary }) {
  const mismatches = [];

  compareSummaryValue({
    mismatches,
    fieldName: "rowCount",
    actualValue: inspection.rowCount,
    summaryValue: summary.rowCount,
  });

  compareSummaryValue({
    mismatches,
    fieldName: "targetKanjiCount",
    actualValue: inspection.targetKanjiCount,
    summaryValue: summary.targetKanjiCount,
  });

  compareSummaryValue({
    mismatches,
    fieldName: "positiveCount",
    actualValue: inspection.positiveCount,
    summaryValue: summary.positiveCount,
  });

  compareSummaryValue({
    mismatches,
    fieldName: "negativeCount",
    actualValue: inspection.negativeCount,
    summaryValue: summary.negativeCount,
  });

  compareSummaryValue({
    mismatches,
    fieldName: "featureCount",
    actualValue: inspection.featureCount,
    summaryValue: summary.featureCount,
  });

  if (
    Array.isArray(summary.featureNames) &&
    !compareArrays(inspection.featureNames, summary.featureNames)
  ) {
    mismatches.push({
      field: "featureNames",
      actual: inspection.featureNames,
      summary: summary.featureNames,
    });
  }

  if (isPlainObject(summary.classificationCounts)) {
    const allClassificationNames = new Set([
      ...Object.keys(inspection.classificationCounts),
      ...Object.keys(summary.classificationCounts),
    ]);

    for (const classificationName of allClassificationNames) {
      compareSummaryValue({
        mismatches,
        fieldName: `classificationCounts.${classificationName}`,
        actualValue: inspection.classificationCounts[classificationName] ?? 0,
        summaryValue: summary.classificationCounts[classificationName] ?? 0,
      });
    }
  }

  return mismatches;
}

function compareSummaryValue({
  mismatches,
  fieldName,
  actualValue,
  summaryValue,
}) {
  if (summaryValue === undefined) {
    return;
  }

  if (actualValue !== summaryValue) {
    mismatches.push({
      field: fieldName,
      actual: actualValue,
      summary: summaryValue,
    });
  }
}

function formatMetric(value) {
  if (value === null || value === undefined) {
    return "n/a";
  }

  return value.toFixed(6);
}

function printInspection({ inspection, validation, summaryMismatches }) {
  const metrics = inspection.descriptorBaselineMetrics;

  console.log("");
  console.log("REFERENCE CANDIDATE BASELINE MODEL DATASET INSPECTION");
  console.log("====================================================");
  console.log(`Dataset: ${inspection.datasetPath}`);
  console.log(`SHA-256: ${inspection.datasetSha256}`);

  console.log("");
  console.log("Dataset");
  console.log("-------");
  console.log(`Rows: ${inspection.rowCount}`);
  console.log(`Unique recognition IDs: ${inspection.uniqueRecognitionIdCount}`);
  console.log(
    `Duplicate recognition IDs: ${inspection.duplicateRecognitionIdCount}`,
  );
  console.log(`Target kanjis: ${inspection.targetKanjiCount}`);
  console.log(`Positive labels: ${inspection.positiveCount}`);
  console.log(`Negative labels: ${inspection.negativeCount}`);
  console.log(`Features in union: ${inspection.featureCount}`);
  console.log(
    `Features per row: min=${inspection.featuresPerRow.minimum}, ` +
      `max=${inspection.featuresPerRow.maximum}, ` +
      `average=${inspection.featuresPerRow.average.toFixed(2)}`,
  );
  console.log(
    `Always-present features: ${inspection.alwaysPresentFeatureCount}`,
  );
  console.log(`Sparse features: ${inspection.sparseFeatureCount}`);

  console.log("");
  console.log("Descriptor baseline");
  console.log("-------------------");
  console.log(`TP: ${metrics.truePositive}`);
  console.log(`TN: ${metrics.trueNegative}`);
  console.log(`FP: ${metrics.falsePositive}`);
  console.log(`FN: ${metrics.falseNegative}`);
  console.log(`Accuracy: ${formatMetric(metrics.accuracy)}`);
  console.log(`Recall: ${formatMetric(metrics.recall)}`);
  console.log(`Specificity: ${formatMetric(metrics.specificity)}`);
  console.log(`Precision: ${formatMetric(metrics.precision)}`);
  console.log(
    `False negative rate: ${formatMetric(metrics.falseNegativeRate)}`,
  );
  console.log(
    `False positive rate: ${formatMetric(metrics.falsePositiveRate)}`,
  );

  console.log("");
  console.log("Potential leakage");
  console.log("-----------------");

  if (inspection.potentialLeakageFeatures.length === 0) {
    console.log("No suspicious feature names detected.");
  } else {
    for (const featureName of inspection.potentialLeakageFeatures) {
      console.log(`- ${featureName}`);
    }
  }

  console.log("");
  console.log("Validation");
  console.log("----------");
  console.log(`Errors: ${validation.errors.length}`);
  console.log(`Warnings: ${validation.warnings.length}`);
  console.log(`Summary mismatches: ${summaryMismatches.length}`);

  if (validation.warnings.length > 0) {
    console.log("");
    console.log("Warnings:");

    for (const warning of validation.warnings) {
      console.log(`- ${warning}`);
    }
  }

  if (summaryMismatches.length > 0) {
    console.log("");
    console.log("Summary mismatches:");

    for (const mismatch of summaryMismatches) {
      console.log(
        `- ${mismatch.field}: actual=${JSON.stringify(
          mismatch.actual,
        )}, summary=${JSON.stringify(mismatch.summary)}`,
      );
    }
  }

  console.log("");
  console.log("Training");
  console.log("--------");
  console.log("Model training has not started in this version.");
}

function validateOptions(options) {
  assertFileExists(options.datasetPath, "ML dataset");

  if (options.requireSummary) {
    assertFileExists(options.summaryPath, "ML dataset summary");
  }
}

function main(argv = process.argv.slice(2)) {
  try {
    const options = parseArguments(argv);

    if (options.help) {
      printHelp();
      return;
    }

    validateOptions(options);

    const datasetEntries = loadJsonlDataset(options.datasetPath);

    const validation = validateDatasetRows(datasetEntries);

    const featureNames = determineFeatureNames(datasetEntries);

    const inspection = buildDatasetInspection({
      datasetPath: options.datasetPath,
      datasetEntries,
      featureNames,
    });

    let summaryMismatches = [];

    if (options.requireSummary) {
      const summary = readJson(options.summaryPath, "ML dataset summary");

      summaryMismatches = compareInspectionWithSummary({
        inspection,
        summary,
      });
    }

    printInspection({
      inspection,
      validation,
      summaryMismatches,
    });

    if (validation.errors.length > 0 || summaryMismatches.length > 0) {
      if (validation.errors.length > 0) {
        console.error("");
        console.error("Dataset validation errors:");

        for (const error of validation.errors) {
          console.error(`- ${error}`);
        }
      }

      process.exitCode = 1;
      return;
    }

    console.log("");
    console.log("Dataset inspection passed.");
  } catch (error) {
    console.error("");
    console.error(`Baseline dataset inspection failed: ${error.message}`);

    process.exitCode = 1;
  }
}

if (require.main === module) {
  main();
}

module.exports = {
  VALID_CLASSIFICATIONS,
  POSITIVE_DESCRIPTOR_CLASSIFICATIONS,
  NEGATIVE_DESCRIPTOR_CLASSIFICATIONS,
  parseArguments,
  calculateFileSha256,
  loadJsonlDataset,
  isPlainObject,
  getExpectedClassification,
  getDescriptorPredictionFromClassification,
  validateDatasetRow,
  validateDatasetRows,
  determineFeatureNames,
  detectPotentialLeakageFeatures,
  calculateFeaturePresence,
  calculateDescriptorMetrics,
  buildDatasetInspection,
  compareArrays,
  compareInspectionWithSummary,
  safeDivide,
  main,
};
